---
abstract: 'Tkx megawidget for scrolled widgets'
author:
  - 'Michael J. Carman <mjcarman@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tkx-Scrolled
provides:
  Tkx::Scrolled:
    file: lib/Tkx/Scrolled.pm
    version: 0.06
requires:
  Tkx: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
